/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  IMAGE SLOTS
 *
 *  Every image on the site is referenced through this file. To swap in real
 *  photography, drop your file into /public/images/ and change the `src` below.
 *  Nothing else needs to change — sizes, cropping and loading are handled by the
 *  components.
 *
 *  See IMAGES.md in the project root for the shot list: exactly what photograph
 *  belongs in each slot, and the crop it needs.
 *
 *  The images currently in place are original brand artwork generated by
 *  scripts/generate-art.py — a consistent "coastal light" family, not stock.
 *  Re-run `python3 scripts/generate-art.py` to regenerate them.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export type ImageSlot = {
  src: string;
  /** Alt text. Describe the image; leave "" only for purely decorative art. */
  alt: string;
};

export const images = {
  /** Homepage hero. Wants a wide, dark-enough frame that white type can sit on. */
  hero: {
    src: "/images/hero/ocean-dusk.jpg",
    alt: "The Pacific at dusk off the Santa Barbara coast, low sun on a calm sea",
  },
  /** Portrait crop of the hero, used on small screens. */
  heroPortrait: {
    src: "/images/hero/ocean-dusk-portrait.jpg",
    alt: "The Pacific at dusk off the Santa Barbara coast",
  },
  /** Philosophy section — tall crop, tactile, quiet. */
  philosophy: {
    src: "/images/coastal/sand.jpg",
    alt: "Wind-rippled sand in low afternoon light",
  },
  /** Expertise / credibility section. */
  expertise: {
    src: "/images/coastal/stone.jpg",
    alt: "Dark wet sea rock, water running across the surface",
  },
  /** Full-bleed immersive break — "Slow down. Breathe deep. Be here." */
  coastalBreak: {
    src: "/images/coastal/morning-water.jpg",
    alt: "Calm open water on a bright Santa Barbara morning",
  },
  /** Secondary immersive band, used on the services and experience pages. */
  tideline: {
    src: "/images/coastal/tideline.jpg",
    alt: "The tideline where foam meets sand, seen from above",
  },
  openWater: {
    src: "/images/coastal/open-water.jpg",
    alt: "Open ocean swell at dusk",
  },
  sand: {
    src: "/images/coastal/sand.jpg",
    alt: "Wind-rippled sand in low afternoon light",
  },
  /** About page hero — wide, editorial. */
  aboutPortrait: {
    src: "/images/hero/shoreline-aerial.jpg",
    alt: "The Santa Barbara shoreline from above, deep water giving way to pale sand",
  },
  /** About page — softer secondary image. */
  aboutLight: {
    src: "/images/about/light.jpg",
    alt: "Warm morning light across a pale surface",
  },
  /** Quiet paper-like ground used behind some sections. */
  paper: {
    src: "/images/texture/paper.jpg",
    alt: "",
  },
  /** Open Graph / social sharing base image. */
  og: {
    src: "/images/og/base.jpg",
    alt: "",
  },
} satisfies Record<string, ImageSlot>;

/**
 * ⚑ REPLACE ME FIRST — a photograph of the practitioner.
 *
 * This is the single highest-impact image on the whole site: people book a
 * person, not a service. Until a real portrait is set, the About page shows a
 * clearly-marked placeholder instead of a stock stand-in.
 *
 * Add e.g. /public/images/about/portrait.jpg and set:
 *   src: "/images/about/portrait.jpg", alt: "…"
 */
export const practitionerPortrait: ImageSlot | null = null;

/** Small blur-up placeholder — a single dark teal pixel, inlined. */
export const blurDataURL =
  "data:image/svg+xml;base64," +
  Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="8" height="8"><rect width="8" height="8" fill="#14384a"/></svg>`,
  ).toString("base64");

/** Pale version, for images that sit on ivory. */
export const blurDataURLLight =
  "data:image/svg+xml;base64," +
  Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="8" height="8"><rect width="8" height="8" fill="#e7ded1"/></svg>`,
  ).toString("base64");
